#!/usr/bin/env python3
"""Split the Claude Enterprise Training Guide into lessons, quiz JSON, and browsers.

Source of truth is the single big guide markdown; everything under train/content/
is derived and regenerated by this script. Run after editing the guide:

    python3 scripts/build-training-content.py
    python3 scripts/build-training-content.py --check   # validate only, write nothing

Chunking follows the segmenting principle: modules are packed into lessons of
roughly TARGET_MINUTES, never splitting a section, so no lesson is a 34-minute
wall of text. Lesson titles are derived from real headings, never invented.
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GUIDE = ROOT / "guide claude enterprise agent.final.md"
OUT = ROOT / "train" / "content"
LESSONS = OUT / "lessons"
HTML_DIR = ROOT / "train"

EXPECTED_MODULES = 23
EXPECTED_QUESTIONS = 100
LESSON_RANGE = (55, 80)          # sanity band for total lessons
WORDS_PER_MINUTE = 220
MIN_MINUTES = 2                  # fold runts shorter than this into the previous lesson
TARGET_MINUTES = 5               # pack sections up to here...
MAX_MINUTES = 9                  # ...and never exceed this in one lesson

# Modules that work better as a searchable tool than as linear reading.
BROWSER_MODULES = {
    "part-17": "mistakes",
    "part-20": "prompts",
    "appendix-a": "glossary",
    "appendix-c": "sheets",
}

SECTION_TO_MODULE = {
    1: "part-02", 2: "part-03", 3: "part-05", 4: "part-06", 5: "part-07",
    6: "part-15", 7: "part-13", 8: "part-12", 9: "part-11", 10: "part-18",
}

PATHS = {
    "new-user": {
        "label": "New user",
        "blurb": "Get productive in Claude in an afternoon.",
        "modules": ["part-01", "part-02", "part-03", "part-04", "part-08", "part-16"],
    },
    "knowledge-worker": {
        "label": "Knowledge worker",
        "blurb": "Apply Claude to your function, with the prompt library at hand.",
        "modules": ["part-01", "part-09", "part-05", "part-06", "part-07", "part-20"],
    },
    "prompt-engineer": {
        "label": "Prompt engineer / power user",
        "blurb": "Context engineering, agentic patterns, and the failure modes to avoid.",
        "modules": ["part-10", "part-11", "part-17", "part-20"],
    },
    "developer": {
        "label": "Developer",
        "blurb": "Claude Code, the API, the Agent SDK, and MCP.",
        "modules": ["part-03", "part-13", "part-14", "part-15"],
    },
    "admin": {
        "label": "Administrator / security",
        "blurb": "Provisioning, audit, compliance, spend control, architecture.",
        "modules": ["part-04", "part-12", "part-17", "part-19"],
    },
    "certification": {
        "label": "Certification candidate",
        "blurb": "The whole guide, in order, then the 100-question exam.",
        "modules": None,
    },
}


def clip(text: str, limit: int) -> str:
    """Trim to a word boundary and drop an unbalanced emphasis marker."""
    flat = re.sub(r"\s+", " ", text).strip()
    if len(flat) > limit:
        flat = flat[:limit].rsplit(" ", 1)[0].rstrip(" ,;:—-") + "…"
    if flat.count("**") % 2:
        flat = flat.replace("**", "", 1)
    if flat.count("`") % 2:
        flat = flat.replace("`", "", 1)
    return flat


def minutes(text: str) -> int:
    return max(1, round(len(text.split()) / WORDS_PER_MINUTE))


def clean_title(title: str) -> str:
    """Strip authoring numbering: '11.1 Installing' -> 'Installing'."""
    t = re.sub(r"^\d+(\.\d+)*\.?\s+", "", title.strip())
    t = re.sub(r"^(Chapter|Part)\s+\d+[:.]\s*", "", t, flags=re.I)
    return t.strip() or title.strip()


def strip_fences(lines):
    """Yield (index, line) for lines outside fenced code blocks."""
    in_fence = False
    for i, line in enumerate(lines):
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if not in_fence:
            yield i, line


# --------------------------------------------------------------------------
# module split
# --------------------------------------------------------------------------

def split_modules(text: str):
    lines = text.split("\n")
    starts = []
    for i, line in strip_fences(lines):
        m = re.match(r"^# (Part (\d+)|Appendix ([ABC])): (.+)$", line)
        if m:
            starts.append((i, m))

    modules = []
    for idx, (line_no, m) in enumerate(starts):
        end = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
        body = "\n".join(lines[line_no:end]).strip() + "\n"
        if m.group(2):
            mid, kind, order = f"part-{int(m.group(2)):02d}", "part", int(m.group(2))
        else:
            mid, kind, order = f"appendix-{m.group(3).lower()}", "appendix", 100 + ord(m.group(3))
        modules.append({
            "id": mid, "kind": kind, "order": order,
            "label": m.group(1), "title": m.group(4).strip(), "body": body,
        })
    modules.sort(key=lambda x: x["order"])
    return modules


def split_sections(body: str):
    """Split a module body into (lede, [sections]) at ## / ### boundaries."""
    lines = body.split("\n")
    heads = []
    for i, line in strip_fences(lines):
        m = re.match(r"^(#{2,3}) (.+)$", line)
        if m:
            heads.append((i, len(m.group(1)), m.group(2).strip()))

    lede_end = heads[0][0] if heads else len(lines)
    lede = "\n".join(lines[1:lede_end]).strip()   # drop the module's own H1

    sections = []
    for idx, (line_no, level, title) in enumerate(heads):
        end = heads[idx + 1][0] if idx + 1 < len(heads) else len(lines)
        chunk_lines = lines[line_no:end]
        chunk = "\n".join(chunk_lines).rstrip()
        if minutes(chunk) > MAX_MINUTES:
            sections.extend(subsplit(chunk_lines, level, title))
        else:
            sections.append({"level": level, "title": title, "text": chunk,
                             "minutes": minutes(chunk)})
    return lede, sections


def subsplit(chunk_lines, level, title):
    """A section too long to be one lesson is split again at #### boundaries."""
    subs = [(i, l[5:].strip()) for i, l in strip_fences(chunk_lines)
            if l.startswith("#### ")]
    if not subs:
        text = "\n".join(chunk_lines).rstrip()
        return [{"level": level, "title": title, "text": text, "minutes": minutes(text)}]

    out = []
    head = "\n".join(chunk_lines[:subs[0][0]]).rstrip()
    for idx, (line_no, sub_title) in enumerate(subs):
        end = subs[idx + 1][0] if idx + 1 < len(subs) else len(chunk_lines)
        text = "\n".join(chunk_lines[line_no:end]).rstrip()
        if idx == 0 and head:
            text = head + "\n\n" + text          # keep the parent heading + intro
        out.append({"level": level, "title": title if idx == 0 else f"{title} — {sub_title}",
                    "text": text, "minutes": minutes(text)})
    return out


EXERCISE_RE = re.compile(r"^#### (Try it[^\n]*)\n+(.*?)(?=\n#{1,6} |\n---\s*$|\Z)", re.M | re.S)
CAVEAT_RE = re.compile(r"^(Caveat[:s].+)$", re.M)


def normalize_blocks(md: str):
    """Promote authored conventions into explicit ::: blocks the renderer knows.

    The guide already marks exercises and caveats; they were being rendered as
    ordinary headings and paragraphs. Converting here keeps the renderer generic
    and makes the transformation visible in the generated lesson files.
    """
    counts = {"exercise": 0, "caution": 0}

    def exercise(m):
        counts["exercise"] += 1
        return ":::exercise " + m.group(1).strip() + "\n" + m.group(2).strip() + "\n:::\n"

    def caution(m):
        counts["caution"] += 1
        return ":::caution\n" + m.group(1).strip() + "\n:::"

    md = EXERCISE_RE.sub(exercise, md)
    md = CAVEAT_RE.sub(caution, md)
    return md, counts


def pack_lessons(module, lede, sections):
    """Greedily pack sections into lessons of ~TARGET_MINUTES, never splitting one."""
    if not sections:
        return [{"index": 1, "title": clean_title(module["title"]),
                 "contains": [], "text": lede, "minutes": max(1, minutes(lede))}]

    groups, current, spent = [], [], 0
    for sec in sections:
        # An H2 always starts a fresh lesson; it marks a real authored boundary.
        hard_break = sec["level"] == 2 and current
        if current and (hard_break or spent + sec["minutes"] > MAX_MINUTES
                        or spent >= TARGET_MINUTES):
            groups.append(current)
            current, spent = [], 0
        current.append(sec)
        spent += sec["minutes"]
    if current:
        groups.append(current)

    # Greedy packing leaves a runt at the end (usually "Chapter summary").
    # Fold anything under MIN_MINUTES back into the lesson before it.
    merged = []
    for group in groups:
        spent = sum(s["minutes"] for s in group)
        if merged and spent < MIN_MINUTES and \
                sum(s["minutes"] for s in merged[-1]) + spent <= MAX_MINUTES:
            merged[-1].extend(group)
        else:
            merged.append(group)
    groups = merged

    lessons = []
    for i, group in enumerate(groups, 1):
        text = "\n\n".join(s["text"] for s in group)
        if i == 1 and lede:
            text = lede + "\n\n" + text
        lessons.append({
            "index": i,
            "title": clean_title(group[0]["title"]),
            "contains": [clean_title(s["title"]) for s in group[1:]],
            "text": text.strip() + "\n",
            "minutes": max(1, minutes(text)),
        })
    return lessons


# --------------------------------------------------------------------------
# quiz
# --------------------------------------------------------------------------

QUESTION_RE = re.compile(r"^\*\*Q(\d+)\.\*\*\s*(.+)$")
OPTION_RE = re.compile(r"^([ABCD])\)\s*(.+)$")
SECTION_RE = re.compile(r"^### Section (\d+) — (.+)$")
ANSWER_RE = re.compile(r"^(\d+)\.\s+\*\*([ABCD])\*\*\s*—\s*(.+)$")


def parse_quiz(appendix_b: str):
    head, _, key_block = appendix_b.partition("### Answer Key")
    if not key_block:
        sys.exit("Appendix B: '### Answer Key' heading not found")

    answers = {}
    for line in key_block.split("\n"):
        m = ANSWER_RE.match(line.strip())
        if m:
            answers[int(m.group(1))] = {"correct": m.group(2), "why": m.group(3).strip()}

    questions, current = [], None
    section_no, section_title = 0, ""
    for line in head.split("\n"):
        stripped = line.strip()
        sm = SECTION_RE.match(stripped)
        if sm:
            section_no, section_title = int(sm.group(1)), sm.group(2).strip()
            continue
        qm = QUESTION_RE.match(stripped)
        if qm:
            current = {"n": int(qm.group(1)), "section": section_no,
                       "sectionTitle": section_title, "q": qm.group(2).strip(),
                       "options": {}}
            questions.append(current)
            continue
        om = OPTION_RE.match(stripped)
        if om and current is not None and om.group(1) not in current["options"]:
            current["options"][om.group(1)] = om.group(2).strip()

    problems = []
    if len(questions) != EXPECTED_QUESTIONS:
        problems.append(f"parsed {len(questions)} questions, expected {EXPECTED_QUESTIONS}")
    if len(answers) != EXPECTED_QUESTIONS:
        problems.append(f"parsed {len(answers)} answers, expected {EXPECTED_QUESTIONS}")

    for q in questions:
        missing = [k for k in "ABCD" if k not in q["options"]]
        if missing:
            problems.append(f"Q{q['n']}: missing options {missing}")
        a = answers.get(q["n"])
        if not a:
            problems.append(f"Q{q['n']}: no answer key entry")
            continue
        q["correct"], q["why"] = a["correct"], a["why"]
        q["options"] = [{"key": k, "text": q["options"].get(k, "")} for k in "ABCD"]

    if sorted(q["n"] for q in questions) != list(range(1, EXPECTED_QUESTIONS + 1)):
        problems.append("question numbering is not a contiguous 1..100 run")
    if problems:
        sys.exit("quiz parse failed:\n  - " + "\n  - ".join(problems))

    sections = {}
    for q in questions:
        sections.setdefault(q["section"],
                            {"n": q["section"], "title": q["sectionTitle"], "count": 0})["count"] += 1
    return questions, [sections[k] for k in sorted(sections)]


def strip_answer_key(appendix_b: str) -> str:
    head, _, _ = appendix_b.partition("### Answer Key")
    return head.rstrip() + (
        "\n\n---\n\n> The answer key lives in the exam, not on this page. "
        "Sit the certification exam to see your score, the correct answers, "
        "and the reasoning behind each one.\n"
    )


# --------------------------------------------------------------------------
# browsers
# --------------------------------------------------------------------------

def parse_prompts(md: str):
    prompts, category = [], ""
    blocks = md.split("\n")
    i = 0
    while i < len(blocks):
        line = blocks[i].strip()
        cm = re.match(r"^### \d+\. (.+)$", line)
        if cm:
            category = cm.group(1).strip()
            i += 1
            continue
        pm = re.match(r"^\*\*(\d+)\. (.+?)\*\*$", line)
        if pm:
            body, pairs, j = [], "", i + 1
            while j < len(blocks) and not blocks[j].startswith("```"):
                j += 1
            if j < len(blocks):
                j += 1
                while j < len(blocks) and not blocks[j].startswith("```"):
                    body.append(blocks[j])
                    j += 1
                j += 1
            while j < len(blocks) and not blocks[j].strip():
                j += 1
            if j < len(blocks):
                pw = re.match(r"^\*Pairs with: (.+?)\.?\*$", blocks[j].strip())
                if pw:
                    pairs = pw.group(1).strip()
            prompts.append({"n": int(pm.group(1)), "title": pm.group(2).strip(),
                            "category": category, "body": "\n".join(body).strip(),
                            "pairs": pairs})
            i = j
            continue
        i += 1
    return prompts


def parse_mistakes(md: str):
    mistakes, category = [], ""
    for line in md.split("\n"):
        stripped = line.strip()
        cm = re.match(r"^### Category \d+: (.+?)(?: \(Mistakes .+?\))?$", stripped)
        if cm:
            category = cm.group(1).strip()
            continue
        mm = re.match(r"^\*\*Mistake (\d+): (.+?)\*\*\s*—\s*(.+)$", stripped)
        if mm:
            rest = mm.group(3).strip()
            body, fix = rest, ""
            fm = re.search(r"\bFix:\s*(.+)$", rest)
            if fm:
                body = rest[:fm.start()].strip().rstrip(".") + "."
                fix = fm.group(1).strip()
            mistakes.append({"n": int(mm.group(1)), "title": mm.group(2).strip(),
                             "category": category, "body": body, "fix": fix})
    return mistakes


def parse_glossary(md: str):
    terms, faq = [], []
    letter, in_faq, faq_category = "", False, ""
    lines = md.split("\n")
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("## ") and "Frequently Asked Questions" in stripped:
            in_faq = True
            continue
        lm = re.match(r"^### ([A-Z])$", stripped)
        if lm and not in_faq:
            letter = lm.group(1)
            continue
        cm = re.match(r"^### \d+\. (.+)$", stripped)
        if cm and in_faq:
            faq_category = cm.group(1).strip()
            continue
        if in_faq:
            qm = re.match(r"^\*\*Q\d+\. (.+?)\*\*$", stripped)
            if qm:
                answer = lines[i + 1].strip() if i + 1 < len(lines) else ""
                faq.append({"q": qm.group(1).strip(), "a": answer, "category": faq_category})
            continue
        tm = re.match(r"^\*\*(.+?)\*\*(?:\s*\((.+?)\))?\s*—\s*(.+)$", stripped)
        if tm and letter:
            terms.append({"term": tm.group(1).strip(), "status": (tm.group(2) or "").strip(),
                          "def": tm.group(3).strip(), "letter": letter})
    return {"terms": terms, "faq": faq}


def parse_sheets(md: str):
    sheets = []
    lines = md.split("\n")
    heads = [(i, l) for i, l in strip_fences(lines) if l.startswith("### ")]
    for idx, (line_no, head) in enumerate(heads):
        end = heads[idx + 1][0] if idx + 1 < len(heads) else len(lines)
        title = head[4:].strip()
        sm = re.match(r"^Sheet (\d+) — (.+)$", title)
        sheets.append({
            "n": int(sm.group(1)) if sm else 90 + idx,
            "title": sm.group(2).strip() if sm else title,
            "body": "\n".join(lines[line_no + 1:end]).strip(),
        })
    return sheets


# --------------------------------------------------------------------------

def git_stamp() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              cwd=ROOT, capture_output=True, text=True,
                              check=True).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "dev"


def bust_cache(stamp: str) -> int:
    pattern = re.compile(r'((?:href|src)="(?:\./)?[\w./-]+\.(?:css|js))\?v=[\w.]+"')
    touched = 0
    for html in sorted(HTML_DIR.glob("*.html")):
        original = html.read_text(encoding="utf-8")
        updated = pattern.sub(rf'\1?v={stamp}"', original)
        if updated != original:
            html.write_text(updated, encoding="utf-8")
            touched += 1
    return touched


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = ap.parse_args()

    if not GUIDE.exists():
        sys.exit(f"guide not found: {GUIDE}")
    text = GUIDE.read_text(encoding="utf-8")

    modules = split_modules(text)
    if len(modules) != EXPECTED_MODULES:
        sys.exit(f"split {len(modules)} modules, expected {EXPECTED_MODULES}")

    by_id = {m["id"]: m for m in modules}
    questions, quiz_sections = parse_quiz(by_id["appendix-b"]["body"])
    by_id["appendix-b"]["body"] = strip_answer_key(by_id["appendix-b"]["body"])

    browsers = {
        "prompts": parse_prompts(by_id["part-20"]["body"]),
        "mistakes": parse_mistakes(by_id["part-17"]["body"]),
        "glossary": parse_glossary(by_id["appendix-a"]["body"]),
        "sheets": parse_sheets(by_id["appendix-c"]["body"]),
    }

    problems = []
    if len(browsers["prompts"]) < 100:
        problems.append(f"prompt library: parsed {len(browsers['prompts'])}, expected >= 100")
    if any(not p["body"] for p in browsers["prompts"]):
        problems.append("prompt library: some prompts have an empty body")
    if len(browsers["mistakes"]) != 100:
        problems.append(f"pitfalls: parsed {len(browsers['mistakes'])}, expected 100")
    if any(not m["fix"] for m in browsers["mistakes"]):
        problems.append("pitfalls: some mistakes have no Fix")
    if len(browsers["glossary"]["terms"]) < 40:
        problems.append(f"glossary: only {len(browsers['glossary']['terms'])} terms")
    if len(browsers["glossary"]["faq"]) < 20:
        problems.append(f"glossary: only {len(browsers['glossary']['faq'])} FAQ entries")
    if len(browsers["sheets"]) < 8:
        problems.append(f"cheat sheets: only {len(browsers['sheets'])}")
    if problems:
        sys.exit("browser parse failed:\n  - " + "\n  - ".join(problems))

    # ---- lessons ----
    manifest_modules, lesson_files, total_lessons = [], {}, 0
    block_counts = {"exercise": 0, "caution": 0}
    for m in modules:
        view = BROWSER_MODULES.get(m["id"])
        lede, sections = split_sections(m["body"])
        module_minutes = minutes(m["body"])

        if view:
            lessons = [{"index": 1, "title": m["title"], "contains": [],
                        "text": m["body"], "minutes": module_minutes}]
        else:
            lessons = pack_lessons(m, lede, sections)

        entries = []
        for lesson in lessons:
            lesson["text"], counts = normalize_blocks(lesson["text"])
            for k, v in counts.items():
                block_counts[k] += v
            lid = m["id"] if view else f"{m['id']}-l{lesson['index']}"
            fname = f"{lid}.md"
            lesson_files[fname] = lesson["text"]
            entries.append({
                "id": lid, "title": lesson["title"], "contains": lesson["contains"],
                "file": f"lessons/{fname}", "minutes": lesson["minutes"], "questions": [],
            })
            total_lessons += 1

        section_no = next((s for s, mid in SECTION_TO_MODULE.items() if mid == m["id"]), None)
        if section_no:
            mine = [q["n"] for q in questions if q["section"] == section_no]
            for pos, qn in enumerate(mine):
                entries[pos % len(entries)]["questions"].append(qn)

        first_para = clip(next((p.strip() for p in lede.split("\n\n") if p.strip()), ""), 320)
        manifest_modules.append({
            "id": m["id"], "label": m["label"], "title": m["title"], "kind": m["kind"],
            "minutes": module_minutes, "quizSection": section_no, "view": view,
            "lede": first_para,
            "lessons": entries,
        })

    if block_counts["exercise"] < 25:
        sys.exit(f"only {block_counts['exercise']} 'Try it' exercises promoted, expected ~33")
    if not LESSON_RANGE[0] <= total_lessons <= LESSON_RANGE[1]:
        sys.exit(f"packed {total_lessons} lessons, expected {LESSON_RANGE[0]}-{LESSON_RANGE[1]}")
    for mod in manifest_modules:
        for lesson in mod["lessons"]:
            if not lesson_files[pathlib.Path(lesson["file"]).name].strip():
                sys.exit(f"{lesson['id']}: empty lesson body")
            if not mod["view"] and lesson["minutes"] > MAX_MINUTES:
                sys.exit(f"{lesson['id']}: {lesson['minutes']} min exceeds the cap")

    module_ids = [m["id"] for m in manifest_modules]
    for path in PATHS.values():
        if path["modules"] is None:
            path["modules"] = list(module_ids)
        unknown = [m for m in path["modules"] if m not in module_ids]
        if unknown:
            sys.exit(f"learning path references unknown modules: {unknown}")

    stamp = git_stamp()
    manifest = {
        "version": stamp, "source": GUIDE.name,
        "modules": manifest_modules, "paths": PATHS,
        "exam": {"total": EXPECTED_QUESTIONS, "passMark": 80, "sectionFloor": 6},
        "review": {"intervalDays": [1, 3, 7, 21]},
        "counts": {
            "lessons": total_lessons,
            "prompts": len(browsers["prompts"]),
            "mistakes": len(browsers["mistakes"]),
            "terms": len(browsers["glossary"]["terms"]),
            "faq": len(browsers["glossary"]["faq"]),
            "sheets": len(browsers["sheets"]),
            "exercises": block_counts["exercise"],
            "caveats": block_counts["caution"],
        },
    }

    if args.check:
        print(f"ok — {len(modules)} modules, {total_lessons} lessons, "
              f"{len(questions)} questions, {len(browsers['prompts'])} prompts, "
              f"{len(browsers['mistakes'])} pitfalls, "
              f"{len(browsers['glossary']['terms'])} terms, "
              f"{len(browsers['sheets'])} sheets, "
              f"{block_counts['exercise']} exercises, version {stamp}")
        return

    OUT.mkdir(parents=True, exist_ok=True)
    LESSONS.mkdir(parents=True, exist_ok=True)
    for stale in list(OUT.glob("*.md")) + list(LESSONS.glob("*.md")):
        stale.unlink()
    for name, body in lesson_files.items():
        (LESSONS / name).write_text(body, encoding="utf-8")

    def dump(name, payload):
        (OUT / name).write_text(
            json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    dump("manifest.json", manifest)
    dump("quiz.json", {"version": stamp, "sections": quiz_sections, "questions": questions})
    dump("prompts.json", {"version": stamp, "prompts": browsers["prompts"]})
    dump("mistakes.json", {"version": stamp, "mistakes": browsers["mistakes"]})
    dump("glossary.json", {"version": stamp, **browsers["glossary"]})
    dump("sheets.json", {"version": stamp, "sheets": browsers["sheets"]})

    busted = bust_cache(stamp)
    avg = round(sum(l["minutes"] for m in manifest_modules for l in m["lessons"]
                    if not m["view"]) / max(1, sum(len(m["lessons"]) for m in manifest_modules
                                                   if not m["view"])), 1)
    print(f"wrote {total_lessons} lessons (avg {avg} min) across {len(modules)} modules, "
          f"{len(questions)} questions, {len(browsers['prompts'])} prompts, "
          f"{len(browsers['mistakes'])} pitfalls, {len(browsers['glossary']['terms'])} terms, "
          f"{len(browsers['sheets'])} sheets; cache-busted {busted} html at v={stamp}")


if __name__ == "__main__":
    main()
