#!/usr/bin/env python3
"""Split the Claude Enterprise Training Guide into per-module markdown + quiz JSON.

Source of truth is the single big guide markdown; everything under train/content/
is derived and regenerated by this script. Run after editing the guide:

    python3 scripts/build-training-content.py
    python3 scripts/build-training-content.py --check   # validate only, write nothing
"""

import argparse
import json
import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
GUIDE = ROOT / "guide claude enterprise agent.final.md"
OUT = ROOT / "train" / "content"
HTML_DIR = ROOT / "train"

EXPECTED_MODULES = 23
EXPECTED_QUESTIONS = 100

# Which quiz section reinforces which module. Sections not listed here only ever
# appear in the final exam.
SECTION_TO_MODULE = {
    1: "part-02",
    2: "part-03",
    3: "part-05",
    4: "part-06",
    5: "part-07",
    6: "part-15",
    7: "part-13",
    8: "part-12",
    9: "part-11",
    10: "part-18",
}

# Learning paths as defined in the guide's "How to Use This Guide" section.
PATHS = {
    "new-user": {
        "label": "New user",
        "blurb": "Get productive in Claude in an afternoon.",
        "modules": ["part-01", "part-02", "part-03", "part-04", "part-08", "part-16"],
    },
    "knowledge-worker": {
        "label": "Knowledge worker",
        "blurb": "Apply Claude to your function, with the prompt library at hand.",
        "modules": ["part-01", "part-09", "part-05", "part-06", "part-07", "part-20"],
    },
    "prompt-engineer": {
        "label": "Prompt engineer / power user",
        "blurb": "Context engineering, agentic patterns, and the failure modes to avoid.",
        "modules": ["part-10", "part-11", "part-17", "part-20"],
    },
    "developer": {
        "label": "Developer",
        "blurb": "Claude Code, the API, the Agent SDK, and MCP.",
        "modules": ["part-03", "part-13", "part-14", "part-15"],
    },
    "admin": {
        "label": "Administrator / security",
        "blurb": "Provisioning, audit, compliance, spend control, architecture.",
        "modules": ["part-04", "part-12", "part-17", "part-19"],
    },
    "certification": {
        "label": "Certification candidate",
        "blurb": "The whole guide, in order, then the 100-question exam.",
        "modules": None,  # filled with every module, in order
    },
}


def read_guide() -> str:
    if not GUIDE.exists():
        sys.exit(f"guide not found: {GUIDE}")
    return GUIDE.read_text(encoding="utf-8")


def split_modules(text: str):
    """Split on top-level '# Part N:' / '# Appendix X:' headings, ignoring fenced code."""
    lines = text.split("\n")
    in_fence = False
    starts = []
    for i, line in enumerate(lines):
        if line.startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        m = re.match(r"^# (Part (\d+)|Appendix ([ABC])): (.+)$", line)
        if m:
            starts.append((i, m))

    modules = []
    for idx, (line_no, m) in enumerate(starts):
        end = starts[idx + 1][0] if idx + 1 < len(starts) else len(lines)
        body = "\n".join(lines[line_no:end]).strip() + "\n"
        if m.group(2):
            mid = f"part-{int(m.group(2)):02d}"
            kind, order = "part", int(m.group(2))
        else:
            mid = f"appendix-{m.group(3).lower()}"
            kind, order = "appendix", 100 + ord(m.group(3))
        modules.append(
            {
                "id": mid,
                "kind": kind,
                "order": order,
                "label": m.group(1),
                "title": m.group(4).strip(),
                "file": f"{mid}.md",
                "body": body,
            }
        )
    modules.sort(key=lambda x: x["order"])
    return modules


QUESTION_RE = re.compile(r"^\*\*Q(\d+)\.\*\*\s*(.+)$")
OPTION_RE = re.compile(r"^([ABCD])\)\s*(.+)$")
SECTION_RE = re.compile(r"^### Section (\d+) — (.+)$")
ANSWER_RE = re.compile(r"^(\d+)\.\s+\*\*([ABCD])\*\*\s*—\s*(.+)$")


def parse_quiz(appendix_b: str):
    """Parse Appendix B into structured questions plus the answer key."""
    head, _, key_block = appendix_b.partition("### Answer Key")
    if not key_block:
        sys.exit("Appendix B: '### Answer Key' heading not found")

    answers = {}
    for line in key_block.split("\n"):
        m = ANSWER_RE.match(line.strip())
        if m:
            answers[int(m.group(1))] = {"correct": m.group(2), "why": m.group(3).strip()}

    questions = []
    section_no, section_title = 0, ""
    current = None
    for line in head.split("\n"):
        stripped = line.strip()
        sm = SECTION_RE.match(stripped)
        if sm:
            section_no, section_title = int(sm.group(1)), sm.group(2).strip()
            continue
        qm = QUESTION_RE.match(stripped)
        if qm:
            current = {
                "n": int(qm.group(1)),
                "section": section_no,
                "sectionTitle": section_title,
                "q": qm.group(2).strip(),
                "options": {},
            }
            questions.append(current)
            continue
        om = OPTION_RE.match(stripped)
        if om and current is not None and om.group(1) not in current["options"]:
            current["options"][om.group(1)] = om.group(2).strip()

    problems = []
    if len(questions) != EXPECTED_QUESTIONS:
        problems.append(f"parsed {len(questions)} questions, expected {EXPECTED_QUESTIONS}")
    if len(answers) != EXPECTED_QUESTIONS:
        problems.append(f"parsed {len(answers)} answers, expected {EXPECTED_QUESTIONS}")

    for q in questions:
        missing = [k for k in "ABCD" if k not in q["options"]]
        if missing:
            problems.append(f"Q{q['n']}: missing options {missing}")
        a = answers.get(q["n"])
        if not a:
            problems.append(f"Q{q['n']}: no answer key entry")
            continue
        q["correct"] = a["correct"]
        q["why"] = a["why"]
        q["options"] = [{"key": k, "text": q["options"].get(k, "")} for k in "ABCD"]

    seen = sorted(q["n"] for q in questions)
    if seen != list(range(1, EXPECTED_QUESTIONS + 1)):
        problems.append("question numbering is not a contiguous 1..100 run")

    if problems:
        sys.exit("quiz parse failed:\n  - " + "\n  - ".join(problems))

    sections = {}
    for q in questions:
        sections.setdefault(
            q["section"], {"n": q["section"], "title": q["sectionTitle"], "count": 0}
        )["count"] += 1

    return questions, [sections[k] for k in sorted(sections)]


def strip_answer_key(appendix_b: str) -> str:
    """Remove the answer key so browsing Appendix B doesn't spoil the exam."""
    head, _, _ = appendix_b.partition("### Answer Key")
    return head.rstrip() + (
        "\n\n---\n\n> The answer key lives in the exam, not on this page. "
        "Sit the certification exam to see your score, the correct answers, "
        "and the reasoning behind each one.\n"
    )


def git_stamp() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "dev"


def bust_cache(stamp: str) -> int:
    """Rewrite ?v= stamps on local asset refs in train/*.html (Hostinger caches 7 days)."""
    pattern = re.compile(r'((?:href|src)="(?:\./)?[\w./-]+\.(?:css|js))\?v=[\w.]+"')
    touched = 0
    for html in sorted(HTML_DIR.glob("*.html")):
        original = html.read_text(encoding="utf-8")
        updated = pattern.sub(rf'\1?v={stamp}"', original)
        if updated != original:
            html.write_text(updated, encoding="utf-8")
            touched += 1
    return touched


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="validate only, write nothing")
    args = ap.parse_args()

    text = read_guide()
    modules = split_modules(text)
    if len(modules) != EXPECTED_MODULES:
        sys.exit(
            f"split {len(modules)} modules, expected {EXPECTED_MODULES}: "
            + ", ".join(m["id"] for m in modules)
        )

    appendix_b = next(m for m in modules if m["id"] == "appendix-b")
    questions, sections = parse_quiz(appendix_b["body"])
    appendix_b["body"] = strip_answer_key(appendix_b["body"])

    module_ids = [m["id"] for m in modules]
    for path in PATHS.values():
        if path["modules"] is None:
            path["modules"] = list(module_ids)
        unknown = [m for m in path["modules"] if m not in module_ids]
        if unknown:
            sys.exit(f"learning path references unknown modules: {unknown}")

    for sec, mod in SECTION_TO_MODULE.items():
        if mod not in module_ids:
            sys.exit(f"quiz section {sec} maps to unknown module {mod}")

    stamp = git_stamp()
    manifest = {
        "version": stamp,
        "source": GUIDE.name,
        "modules": [
            {
                "id": m["id"],
                "label": m["label"],
                "title": m["title"],
                "file": m["file"],
                "kind": m["kind"],
                "minutes": max(3, round(len(m["body"].split()) / 220)),
                "quizSection": next(
                    (s for s, mid in SECTION_TO_MODULE.items() if mid == m["id"]), None
                ),
            }
            for m in modules
        ],
        "paths": PATHS,
        "exam": {"total": EXPECTED_QUESTIONS, "passMark": 80, "sectionFloor": 6},
    }

    if args.check:
        print(
            f"ok — {len(modules)} modules, {len(questions)} questions, "
            f"{len(sections)} sections, version {stamp}"
        )
        return

    OUT.mkdir(parents=True, exist_ok=True)
    for stale in OUT.glob("*.md"):
        stale.unlink()
    for m in modules:
        (OUT / m["file"]).write_text(m["body"], encoding="utf-8")

    (OUT / "manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (OUT / "quiz.json").write_text(
        json.dumps(
            {"version": stamp, "sections": sections, "questions": questions},
            indent=2, ensure_ascii=False,
        ) + "\n",
        encoding="utf-8",
    )

    busted = bust_cache(stamp)
    print(
        f"wrote {len(modules)} modules + quiz.json ({len(questions)} questions) "
        f"to {OUT.relative_to(ROOT)}; cache-busted {busted} html file(s) at v={stamp}"
    )


if __name__ == "__main__":
    main()
